---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cm2c-user
  namespace: {{ .Release.Namespace }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: cm2c-role
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - list

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cm2c-user-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: cm2c-user
  apiGroup: ""
roleRef:
  kind: Role
  name: cm2c-role
  apiGroup: ""