#!/bin/sh

echo "CM2C_INTERVAL:        $CM2C_INTERVAL"
echo "CM2C_LOG_LEVEL:       $CM2C_LOG_LEVEL"
echo "CM2C_NAMESPACE:       $CM2C_NAMESPACE"
echo "CM2C_LABEL_SELECTOR:  $CM2C_LABEL_SELECTOR"
echo "CM2C_CONSUL_URL:      $CM2C_CONSUL_URL"
echo "CM2C_CONSUL_PATH:     $CM2C_CONSUL_PATH"
echo "CM2C_MODE:            $CM2C_MODE"


LABEL_SELECTOR=""

if [ "${CM2C_LABEL_SELECTOR}" != "" ]
then
  LABEL_SELECTOR="-l ${CM2C_LABEL_SELECTOR}"
  echo "LABEL_SELECTOR:       $LABEL_SELECTOR"
fi

configmap2consul -c ${CM2C_CONSUL_URL} -m ${CM2C_MODE} -i ${CM2C_INTERVAL} -n ${CM2C_NAMESPACE} -p ${CM2C_CONSUL_PATH} ${LABEL_SELECTOR}